#!/usr/bin/env sh

runtime_path="/run/enroot/user-$SLURM_JOB_UID"
mkdir -p "$runtime_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$runtime_path"
chmod 0775 "$(dirname "$runtime_path")"
chmod 0700 "$runtime_path"

cache_path="/mnt/scratch/tmp/enroot/cache/group-$(id -g "$SLURM_JOB_UID")"
mkdir -p "$cache_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$cache_path"
chmod -R 0770 "$cache_path"
chmod 777 "/mnt/scratch/tmp/enroot/cache/"

data_path="/mnt/scratch/tmp/enroot/containers/user-$SLURM_JOB_UID"
mkdir -p "$data_path"
chown "$SLURM_JOB_UID:$(id -g "$SLURM_JOB_UID")" "$data_path"
chmod 0700 "$data_path"
chmod 777 "/mnt/scratch/tmp/enroot/containers/"

echo "export ENROOT_RUNTIME_PATH=/run/enroot/user-$SLURM_JOB_UID"
echo "export ENROOT_CACHE_PATH=/opt/cache/enroot/group-$(id -g "$SLURM_JOB_UID")"
echo "export ENROOT_DATA_PATH=/mnt/scratch/tmp/enroot/containers/user-$SLURM_JOB_UID"
