#!/bin/bash -ex

#-- Create entry in fstab to mount our 2 local nvme disks
cat <<END >>/etc/fstab
nfs.example.com:/srv/nfs/ldap-users /home/ldap-users nfs defaults 0 0
nfs.example.com:/srv/nfs/compute-nodes/enroot-cache /opt/cache/enroot nfs defaults 0 0
nfs.example.com:/srv/nfs/persistent /mnt/nfs nfs defaults 0 0
UUID=ec32b960-14df-472a-9ecc-5dac105411c2 /mnt/disk xfs defaults,nofail,x-systemd.device-timeout=30 0 0
END

#-- Set dirs and perms for enroot and pyxis
mkdir -p /mnt/disk
chmod 755 /mnt/disk
mkdir -p /mnt/nfs
chmod 755 /mnt/nfs
mkdir -p -m755 /home/ldap-users
mkdir -p -m755 /opt/cache
mkdir -p -m755 /opt/cache/enroot
ln -s /mnt/nfs/cache/shared /opt/cache/shared                   # STORAGE_PATH
ln -s /mnt/nfs/cache/persistent /opt/cache/persistent           # DEEPSQUARE_TMP or DEEPSQUARE_SHARED_TMP
ln -s /mnt/nfs/cache/world-tmp /opt/cache/world-tmp             # DEEPSQUARE_SHARED_WORLD_TMP
ln -s /mnt/disk/persistent/per-user/tmp /opt/cache/disk/tmp     # DEEPSQUARE_DISK_TMP
ln -s /mnt/disk/persistent/shared/tmp /opt/cache/disk/world-tmp # DEEPSQUARE_DISK_WORLD_TMP
ln -s /mnt/disk/persistent /mnt/persistent
ln -s /mnt/disk/scratch /mnt/scratch

mkdir -p -m777 "/run/enroot"
mkdir -p -m755 "/var/run/munge"
chown -R munge: "/var/run/munge/"
chown munge: "/var/lib/munge/"
chmod 0700 "/var/lib/munge/"
chown -R munge: "/etc/munge/"
mkdir -p /var/log/munge
chown -R munge:munge /var/log/munge
chmod 700 /var/log/munge

#Mount all the fstab
mount -a || echo "mount -a has some errors but we ignored it"

# Scratch (for container runtimes)
mkdir -p /mnt/disk/scratch
chmod 755 /mnt/disk/scratch
rm -rf /mnt/disk/scratch/tmp
mkdir -p -m777 /mnt/disk/scratch/tmp
mkdir -p -m777 /mnt/disk/scratch/tmp/apptainer/
mkdir -p -m777 /mnt/disk/scratch/tmp/enroot/

# Caches
mkdir -p /mnt/nfs/cache
chmod 755 /mnt/nfs/cache
mkdir -p /mnt/nfs/cache/shared
chmod 777 /mnt/nfs/cache/shared
mkdir -p /mnt/nfs/cache/persistent # DEEPSQUARE_TMP or DEEPSQUARE_SHARED_TMP (cache is not cleared, this must be cleared via cron)
chmod 777 /mnt/nfs/cache/persistent
mkdir -p /mnt/nfs/cache/world-tmp # DEEPSQUARE_SHARED_WORLD_TMP (cache is not cleared, this must be cleared via cron)
chmod 777 /mnt/nfs/cache/world-tmp

mkdir -p /mnt/disk/persistent
chmod 755 /mnt/disk/persistent

mkdir -p /mnt/disk/persistent/per-user
chmod 755 /mnt/disk/persistent/per-user
rm -rf /mnt/disk/persistent/per-user/tmp
mkdir -p -m777 /mnt/disk/persistent/per-user/tmp # DEEPSQUARE_DISK_TMP

mkdir -p /mnt/disk/persistent/shared
chmod 755 /mnt/disk/persistent/shared
rm -rf /mnt/disk/persistent/shared/tmp
mkdir -p -m777 /mnt/disk/persistent/shared/tmp # DEEPSQUARE_DISK_WORLD_TMP

echo "APPTAINER_TMPDIR=/mnt/scratch/tmp/apptainer/" >>/etc/environment
