#!/bin/sh

VERSION=$(curl -fsSL -H "Authorization: Bearer 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" https://raw.githubusercontent.com/deepsquare-io/the-grid/main/latest | grep "grid-logger" | sed -E 's/.*=(.*)/\1/g')

URL=$(curl -fsSL \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer 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"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/deepsquare-io/the-grid/releases/tags/grid-logger-${VERSION}" | jq -r '.assets[] | select(.name=="grid-logger-writer-linux-amd64") | .url')

curl -fsSL \
  -H "Accept: application/octet-stream" \
  -H "Authorization: Bearer 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" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "${URL}" \
  -o /usr/local/bin/grid-logger-writer

chmod +x /usr/local/bin/grid-logger-writer
