#!/usr/bin/bash

arch="$(uname -m)"

if [[ $arch == x86_64* ]]; then
    curl -fsSL https://github.com/deepsquare-io/proxy/releases/download/v0.2.0/dpsproxy-linux-amd64 -o /usr/bin/dpsproxy
elif [[ $arch == arm* ]] || [[ $arch = aarch64 ]]; then
    curl -fsSL https://github.com/deepsquare-io/proxy/releases/download/v0.2.0/dpsproxy-linux-arm64 -o /usr/bin/dpsproxy
fi

chmod +x /usr/bin/dpsproxy
