#!/bin/bash

set -ex

#nvidia-xconfig -a --allow-empty-initial-configuration --cool-bits=31 --use-display-device="DFP-0" --connected-monitor="DFP-0"

git clone https://github.com/keylase/nvidia-patch.git /tmp/nvidia-patch
cd /tmp/nvidia-patch
chmod +x ./patch.sh
./patch.sh
cd /
rm -rf /tmp/nvidia-patch
